name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    strategy:
      matrix:
        repository: ["chatjs", "chat-interface", "chat-ui-examples"]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          template: repository
          filename: ${{ matrix.repository }}-metrics.repository.svg
          user: amazon-connect
          repo: amazon-connect-${{ matrix.repository }}
          plugin_lines: yes
          plugin_followup: yes

